---

- name: "Setup"
  hosts: localhost
  connection: local

  roles:
    - role: ansible-role-docker-ce

  tasks:
    - name: "Update"
      become: yes
      dnf:
        name: "*"
        state: latest

    - name: Install basic packages
      become: yes
      dnf:
        name:
          - git
          - vim
          - fish
          - chromium
          - gparted
          - htop
          - terminator
          - rpmfusion-packager
          - rpmfusion-free-release
          - remi-release
          - snapd
          - golang-bin
          - docker-compose
          - dnf-plugins-core
          - google-chrome-stable
          - chromium
          - curl
          - wget
          - qbittorrent

    - name: "PHP Packages"
      become: yes
      dnf:
        name:
          - php-cli
          - php-mcrypt
          - php-bcmath
          - php-zip
          - php-pdo
          - php-mysqlnd
          - php-dom
          - php-json
          - php-mbstring
          - php-gd

    - name: "Current User"
      become: false
      local_action: command whoami
      register: username_on_the_host

    - name: Configure User "{{ username_on_the_host.stdout }}"
      become: true
      user:
        name: "{{ username_on_the_host.stdout }}"
        shell: /usr/bin/fish
        groups: docker
        append: yes

    - name: Install Snap Packages
      become: true
      snap:
        name:
          - phpstorm
          - vscode
          - spotify
          - obs-studio
          - zoom-client
          - slack
          - riot-web
        classic: yes
